# Generated by Django 5.1.5 on 2026-03-02 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tips", "Tips & Tricks"),
                            ("case_study", "Case Study"),
                            ("news", "Industry News"),
                            ("how_to", "How-To Guide"),
                            ("inspirational", "Inspirational"),
                            ("trending", "Trending Topic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("witty", "Witty"),
                            ("inspirational", "Inspirational"),
                            ("educational", "Educational"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("angle", models.TextField()),
                ("pain_point", models.TextField(blank=True)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_used", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                (
                    "hashtags",
                    models.TextField(blank=True, help_text="Comma-separated hashtags"),
                ),
                ("quality_score", models.FloatField(default=0.0)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Needs Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("engagement_notes", models.TextField(blank=True)),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="content.contentidea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_type", models.CharField(max_length=50)),
                ("score", models.FloatField()),
                ("issues", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="content.generatedcontent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_entries",
                        to="content.generatedcontent",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "scheduled_time"],
                "unique_together": {("scheduled_date", "scheduled_time", "platform")},
            },
        ),
    ]
